#!/bin/bash

echo "🚀 Deploying Working Backend to Render.com..."
echo "📋 This will fix your registration issue!"

echo ""
echo "🔧 Step 1: Go to Render.com"
echo "Visit: https://render.com"
echo "Sign up/Login with GitHub"

echo ""
echo "📁 Step 2: Create New Web Service"
echo "1. Click 'New +' → 'Web Service'"
echo "2. Connect GitHub repo: somtonweke1/TrustStack"
echo "3. Configure:"
echo "   - Name: truststack-api"
echo "   - Environment: Node"
echo "   - Build Command: cd server && npm install"
echo "   - Start Command: cd server && npm start"
echo "   - Plan: Free"

echo ""
echo "🗄️ Step 3: Add PostgreSQL Database"
echo "1. Go back to dashboard"
echo "2. 'New +' → 'PostgreSQL'"
echo "3. Name: truststack-db"
echo "4. Plan: Free"
echo "5. Copy Internal Database URL"

echo ""
echo "⚙️ Step 4: Set Environment Variables"
echo "In your web service, add:"
echo "NODE_ENV=production"
echo "PORT=10000"
echo "JWT_SECRET=your-super-secret-jwt-key"
echo "BCRYPT_ROUNDS=12"
echo "DATABASE_URL=(the URL from step 3)"

echo ""
echo "🚀 Step 5: Deploy"
echo "Click 'Create Web Service'"
echo "Wait 2-3 minutes for build"

echo ""
echo "✅ Result: Registration will work on Vercel!"
echo "🔗 Your Vercel: https://trust-stack.vercel.app"
echo "🔌 Your API: https://truststack-api.onrender.com"
